# -*- mode: ruby -*-
# vi: set ft=ruby :

# configuration for Redmine server
Vagrant.configure(2) do |config|
  # virtualbox
  config.vm.box = "centos65"

  # networking
  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.network "private_network", ip: "192.168.74.11", virtualbox__intnet: "vagrant"
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end
  
  # synced folders
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "shared/", "/shared", create: true, owner: "vagrant", group: "vagrant"
  
  # provisioning
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
  end
end
